package com.freelanzer.aws.functions;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Jobs")
public class Job implements Serializable {

	private static final long serialVersionUID = 5577921774661729775L;

	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute
	private String uiid;

	@DynamoDBHashKey
	@DynamoDBAttribute
	private int id;

	@DynamoDBAttribute
	private String userId;

	@DynamoDBAttribute
	private String jobName;

	@DynamoDBAttribute
	private String summary;

	public Job() {

	}

	public Job(String uiid, int id, String userId, String jobName, String summary) {
		super();
		this.uiid = uiid;
		this.id = id;
		this.userId = userId;
		this.jobName = jobName;
		this.summary = summary;
	}

	public String getUiid() {
		return uiid;
	}

	public void setUiid(String uiid) {
		this.uiid = uiid;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getJobName() {
		return jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

}
